docs: Add "How this Works" section.
xdbob/sway-services pull request #19
Opened 2021-01-11 18:39 UTC by markstos

Even as someone who has a strong understanding of `systemd`, I found I
needed to read through many of the source files here to get a basic
understanding of how all the pieces fit together.

To make it faster for other's I've created a brief "tour" of the project
with a new "How this works" section in the README.

I've also clarified that the provided units are not enabled by default
and explained how to additional systemd services to run for Sway.

2021-02-13 01:15 UTC, jtheoof commented
This is pretty nice. Would love to have this merged @xdbob

2023-04-06 08:06 UTC, xdbob requested changes

2023-04-06 08:06 UTC, xdbob commented on README.md
> +The provided services are not enabled by default. If you want enable `mako` example,
I apologize since I wasn't active the previous years. could you replace `mako` by a provided unit please ?

2023-05-16 19:07 UTC, markstos commented
I switched to `sway-systemd` instead.

2023-05-16 19:07 UTC, closed without merging